### ISSUE TITLE
Problems with Ember CLI 2.4.2

### ISSUE THREAD

**Issue by kmmathis** [lifegadget/ember-cli-bootstrap-sassy#36]
Just upgraded my project to the latest Ember CLI (2.4.2 at the time of this issue) and I'm getting the following error when specifying specific JS modules in ember-cli-build.js. When I remove the 'js' array from the build file, everything works fine.

``` js
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    'ember-cli-bootstrap-sassy': {
      'js': ['collapse', 'button','dropdown','modal','tab'],
      'glyphicons': false
    }
  });

  return app.toTree();
};

```

```
version: 2.4.2
bootstrap-sassy config: some JS loaded [collapse,button,dropdown,modal,tab], glyphicons disabled
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT, no such file or directory '/Users/kmmathis/Projects/pi-property-search/tmp/source_map_concat-input_base_path-tudm1UIh.tmp/0/undefinedjavascripts/bootstrap/collapse.js'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at ConcatWithMaps.keyForFile (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at:
    at ConcatWithMaps.Plugin (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:21:10)
    at new ConcatWithMaps (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:22:17)
    at module.exports (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/lib/broccoli/ember-app.js:329:10)
    at EmberApp.javascript (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/lib/broccoli/ember-app.js:1190:12)
    at EmberApp.toArray (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/lib/broccoli/ember-app.js:1542:10)
    at EmberApp.toTree (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:30)
    at module.exports (/Users/kmmathis/Projects/pi-property-search/ember-cli-build.js:31:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/kmmathis/Projects/pi-property-search/node_modules/ember-cli/lib/models/builder.js:55:19)
```

**Comment by yankeeinlondon** [comment]
It appears something is interfering with getting the "bowerDirectory". Can you try going into the `ember-cli-bootstrap-sassy/index.js` and modifying line 9 to:

```
 var target = app;
```

Let's see if that works. Also another interesting troubleshooting step would be to output the value of `this.bootstrapPath` both at line 21 and 49.

**Comment by kmmathis** [comment]
Modifying line 9 seemingly has no effect. The value of `this.bootstrapPath` is the same on both lines: `bower_components/bootstrap-sass/assets/`

**Comment by yankeeinlondon** [comment]
ok, and you've checked that you have `bower_components/bootstrap-sass/assets` directory, right?

**Comment by kmmathis** [comment]
Yup, just double checked and it's there

**Comment by yankeeinlondon** [comment]
maybe it's time for `rm -rf node_modules tmp dist` with a `npm cache clean` before reinstalling npm modules? Sorry, driving a bit blind at the moment.

**Comment by kmmathis** [comment]
I figured out what's going on. Seems to be a scope issue. The call to `this` on line 22 inside the import method isn't referencing the scope of the `included` property. Doing something like

`var self = this;`

and then

`target.import(self.bootstrapPath + 'javascripts/bootstrap/' + fileName + '.js');`

fixes the issue

**Comment by yankeeinlondon** [comment]
Great, nice work. Do you want to send me a PR for that?

**Comment by kmmathis** [comment]
I was on my way to do that, but then I noticed that the `index.js` file in my node_modules folder is a different version than the `index.js` file in the repo. I've cleared the cache and tried uninstalled and re-installing the addon, but I keep getting a different version. Any insight on why that might be happening?

The entry in package.json is:

`"ember-cli-bootstrap-sassy": "0.5.2",`

**Comment by kmmathis** [comment]
FWIW, replacing my local index.js with the index.js from this repo fixed the issue I was having. I have a feeling this is some silly mistake I've made.

**Comment by yankeeinlondon** [comment]
Well yes I see what's happening the last pushed repo version was npm `0.5.1` and I must have published `0.5.2` without pushing the local commit. Admittedly this "fix" seems to be contributing to your woes. The fix _was intended_ to allow for addon's to cascade down to the application

**Comment by yankeeinlondon** [comment]
Let me push it up and then if you apply the PR then hopefully we'll have solved your problem at the same time as making it cascade-friendly at the same time.

**Comment by yankeeinlondon** [comment]
I've pushed back up to Origin.

**Comment by kmmathis** [comment]
Thank you!
