### ISSUE TITLE
Not supported NPM v3?

### ISSUE THREAD

**Issue by shijistar** [lifegadget/ember-cli-bootstrap-sassy#45]
I'm using node v6.9.5 which integrates NPM v3. When I try to run my ember project, I got the following error: 

```
Error: Attempting to watch missing directory: node_modules/ember-cli-bootstrap-sassy/node_modules/bootstrap-sass/assets/stylesheets
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/home/user/Documents/udesk_bi_web/node_modules/ember-cli-broccoli-sane-watcher/index.js:142:11)
    at /home/user/Documents/udesk_bi_web/node_modules/broccoli-builder/lib/builder.js:132:35
    at tryCatch (/home/user/Documents/udesk_bi_web/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/user/Documents/udesk_bi_web/node_modules/rsvp/dist/rsvp.js:553:13)
    at /home/user/Documents/udesk_bi_web/node_modules/rsvp/dist/rsvp.js:628:16
    at flush (/home/user/Documents/udesk_bi_web/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at SassCompiler.Plugin (/home/user/Documents/udesk_bi_web/node_modules/broccoli-plugin/index.js:7:31)
    at SassCompiler.CachingWriter [as constructor] (/home/user/Documents/udesk_bi_web/node_modules/broccoli-sass-source-maps/node_modules/broccoli-caching-writer/index.js:18:10)
    at new SassCompiler (/home/user/Documents/udesk_bi_web/node_modules/broccoli-sass-source-maps/index.js:20:17)
    at /home/user/Documents/udesk_bi_web/node_modules/ember-cli-sass/index.js:39:12
    at Array.map (native)
    at SASSPlugin.toTree (/home/user/Documents/udesk_bi_web/node_modules/ember-cli-sass/index.js:36:34)
    at /home/user/Documents/udesk_bi_web/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/home/user/Documents/udesk_bi_web/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessCss (/home/user/Documents/udesk_bi_web/node_modules/ember-cli-preprocess-registry/preprocessors.js:148:10)
```

I guess it could be related to the new file structure of npm v3, but I'm not quite sure. Anyone can help? I can't startup my project. Thank you very much.

**Comment by yankeeinlondon** [comment]
Did you ever solve this? Sorry but I'm not using this addon anymore (even though I authored back in the day). I'm using `ui-bootstrap` instead which uses Bootstrap 4.x. Very happy to take a PR if you have solved this.

**Comment by zoltan-nz** [comment]
Ember-cli-bootstrap-sassy is compatible with Node.js v4 and Node.js v6 and Node.js v8. It is not an issue anymore. I think, this issue can be closed. ;)

**Comment by yankeeinlondon** [comment]
Agreed. Thanks for being my eyes and ears. Haven’t been doing any Ember lately so my attention has wondered.
