### ISSUE TITLE
ember 2.14.0 fastboot problem "Error: Bootstrap's JavaScript requires jQuery"

### ISSUE THREAD

**Issue by tarponjargon** [lifegadget/ember-cli-bootstrap-sassy#50]
I just upgraded from 2.13.1 to 2.14.0 and am getting this error, which prevents my app from running.  If I use: http://localhost:4200/?fastboot=false the app runs normally.  I also tried uninstalling ember-cli-bootstrap-sassy and the app *does* run in fastboot (albeit it's very ugly w/o bootstrap).

Hopefully I'm not barking up the wrong tree here.  Any help appreciated!  Full error below:

```
Error: Bootstrap's JavaScript requires jQuery
    at /Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-u4FmJUgL.tmp/assets/vendor/bootstrap/javascripts/bootstrap.js:8:1
    at ContextifyScript.Script.runInContext (vm.js:37:29)
    at VMSandbox.eval (/Volumes/Home/Sites/searchapp/node_modules/fastboot/src/vm-sandbox.js:14:14)
    at /Volumes/Home/Sites/searchapp/node_modules/fastboot/src/ember-app.js:142:15
    at Array.forEach (native)
    at EmberApp.loadAppFiles (/Volumes/Home/Sites/searchapp/node_modules/fastboot/src/ember-app.js:139:21)
    at EmberApp.retrieveSandboxedApp (/Volumes/Home/Sites/searchapp/node_modules/fastboot/src/ember-app.js:187:10)
    at new EmberApp (/Volumes/Home/Sites/searchapp/node_modules/fastboot/src/ember-app.js:50:21)
    at FastBoot._buildEmberApp (/Volumes/Home/Sites/searchapp/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Volumes/Home/Sites/searchapp/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Volumes/Home/Sites/searchapp/node_modules/ember-cli-fastboot/index.js:247:29)
    at Layer.handle [as handle_request] (/Volumes/Home/Sites/searchapp/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Volumes/Home/Sites/searchapp/node_modules/express/lib/router/index.js:317:13)
    at /Volumes/Home/Sites/searchapp/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Volumes/Home/Sites/searchapp/node_modules/express/lib/router/index.js:335:12)
    at next (/Volumes/Home/Sites/searchapp/node_modules/express/lib/router/index.js:275:10)
    at err (/Volumes/Home/Sites/searchapp/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/Volumes/Home/Sites/searchapp/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatch (/Volumes/Home/Sites/searchapp/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:12)
    at invokeCallback (/Volumes/Home/Sites/searchapp/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:13)
    at /Volumes/Home/Sites/searchapp/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/Volumes/Home/Sites/searchapp/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by tarponjargon** [comment]
As a test I created an ember-quickstart project:

```
ember new ember-quickstart
cd ember-quickstart
ember install ember-cli-bootstrap-sassy
ember install ember-cli-fastboot
ember serve
```

And I get the same "Error: Bootstrap's JavaScript requires jQuery" error as post above. 

if I uninstall ember-cli-bootstrap-sassy:

`npm uninstall ember-cli-bootstrap-sassy --save-dev`

Everything works.

versions:

```
ember-cli: 2.14.0
node: 7.2.1
os: darwin x64
```

**Comment by yankeeinlondon** [comment]
I'm not using Fastboot so my hands on experience is zero but I believe that Bootstrap 3.x (if not 4.x) has some JS dependencies that depend on JQuery. So in essence I think the error is a result of these deps not on this addon specifically. 

I have been using Bootstrap 4.x and in this case I really don't use any of the JS dependencies of Bootstrap (see my `ui-bootstrap` addon for my 4.x implementation). You could likely do the same for this plugin by turning off the JS dependencies (see the README).

Hope this helps and if you find that turning off the JS deps doesn't work for you I'm happy to take a PR.

**Comment by tarponjargon** [comment]
So yeah, adding this option to `ember-cli-build.js`:

```
  let app = new EmberApp(defaults, {
    // Add options here
	'ember-cli-bootstrap-sassy': {
	  'js': false
	}
  });
```

Does work.  

I'm not sure exactly what changed with the latest version of fastboot, but the prior version was not bothered about bootstrap JS being enabled with this plugin.

I actually was using some of that bootstrap JS (for menus), so I guess I'll need to rewrite that to be more ember-y.  Which I should have done in the first place.

I was looking into how to set that option to true for the build in the browser scope only, and there *used* to be a way, it would have been something like this:

```
  if (process.env.EMBER_CLI_FASTBOOT) {
	  app.options['ember-cli-bootstrap-sassy']['js'] = false;
  }
```
(in ember-cli-build.js)  But that was deprecated: https://github.com/ember-fastboot/ember-cli-fastboot#build-hooks-for-fastboot

It *seems* to say that it should still be possible:

> There are two places where the inclusion of incompatible JavaScript libraries could occur:
> 
> app.import in the application's ember-cli-build.js
> app.import in an addon's included hook

But in fact, it's not possible in the build file:
https://github.com/ember-fastboot/ember-cli-fastboot/issues/433

Ah well.  Thanks for your help though!

**Comment by zoltan-nz** [comment]
Fastboot compatibility is implemented, so this issue could be closed. ;)
